# Generated by Django 5.2.8 on 2025-12-06 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_session_options_and_more'),
        ('families', '0004_auto_20251206_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='families.child', verbose_name='Child')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Ticket',
                'verbose_name_plural': 'Event Tickets',
                'db_table': 'event_tickets',
                'indexes': [models.Index(fields=['child'], name='event_ticke_child_i_22981b_idx'), models.Index(fields=['event'], name='event_ticke_event_i_2e2bb6_idx')],
                'unique_together': {('child', 'event')},
            },
        ),
        migrations.CreateModel(
            name='SessionTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tickets', to='families.child', verbose_name='Child')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tickets', to='events.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Session Ticket',
                'verbose_name_plural': 'Session Tickets',
                'db_table': 'session_tickets',
                'indexes': [models.Index(fields=['child'], name='session_tic_child_i_c5a7b7_idx'), models.Index(fields=['session'], name='session_tic_session_e3a009_idx')],
                'unique_together': {('child', 'session')},
            },
        ),
    ]
