# Generated by Django 5.2.8 on 2025-12-06 17:25

from django.db import migrations


def migrate_tickets_to_polymorphic(apps, schema_editor):
    """
    Migrate existing Ticket records to the new polymorphic structure:
    - EVENT_PASS → EventTicket (linked to the event via session.event)
    - SESSION_TICKET → SessionTicket (linked directly to session)
    - NONE → Delete (children with no tickets should have no ticket record)
    """
    Ticket = apps.get_model('events', 'Ticket')
    EventTicket = apps.get_model('events', 'EventTicket')
    SessionTicket = apps.get_model('events', 'SessionTicket')

    for old_ticket in Ticket.objects.all():
        if old_ticket.type == 'EVENT_PASS':
            # Event passes should link to the event
            # We need to get the event from the session if session exists
            if old_ticket.session:
                event = old_ticket.session.event
                EventTicket.objects.get_or_create(
                    child=old_ticket.child,
                    event=event,
                )
            # If no session, we can't determine the event, so skip this ticket
            # This shouldn't happen in practice based on the current data model

        elif old_ticket.type == 'SESSION_TICKET':
            # Session tickets link directly to the session
            if old_ticket.session:
                SessionTicket.objects.get_or_create(
                    child=old_ticket.child,
                    session=old_ticket.session,
                )
            # If no session, skip (shouldn't happen for SESSION_TICKET)

        elif old_ticket.type == 'NONE':
            # Children with no tickets should have no record - just skip/delete
            pass


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by recreating old Ticket records from polymorphic models.
    This is for rollback purposes.
    """
    Ticket = apps.get_model('events', 'Ticket')
    EventTicket = apps.get_model('events', 'EventTicket')
    SessionTicket = apps.get_model('events', 'SessionTicket')

    # Recreate EVENT_PASS tickets
    for event_ticket in EventTicket.objects.all():
        # For EVENT_PASS, we need to pick a session from the event
        # This is imperfect but necessary for reverse migration
        session = event_ticket.event.sessions.first()
        if session:
            Ticket.objects.get_or_create(
                child=event_ticket.child,
                session=session,
                defaults={'type': 'EVENT_PASS'},
            )

    # Recreate SESSION_TICKET tickets
    for session_ticket in SessionTicket.objects.all():
        Ticket.objects.get_or_create(
            child=session_ticket.child,
            session=session_ticket.session,
            defaults={'type': 'SESSION_TICKET'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventticket_sessionticket'),
    ]

    operations = [
        migrations.RunPython(migrate_tickets_to_polymorphic, reverse_migration),
    ]
