# Generated by Django 5.2.8 on 2026-03-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_migrate_old_tickets_to_polymorphic'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='external_ticket_code',
            field=models.CharField(blank=True, help_text='ETicket code from the external registration system.', max_length=255, null=True, verbose_name='External Ticket Code'),
        ),
        migrations.AddField(
            model_name='sessionticket',
            name='external_ticket_code',
            field=models.CharField(blank=True, help_text='ETicket code from the external registration system.', max_length=255, null=True, verbose_name='External Ticket Code'),
        ),
    ]
