# Generated by Django 5.2.8 on 2026-07-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_repoint_tickets_to_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent_checkin_policy_default',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('open', 'Open (no ticket required)'), ('ticket_required', 'Ticket required')], default='open', help_text="Applied to sessions of this event that don't set their own policy.", max_length=20, verbose_name='Default Parent Check-In Policy'),
        ),
        migrations.AddField(
            model_name='session',
            name='parent_checkin_policy',
            field=models.CharField(blank=True, choices=[('disabled', 'Disabled'), ('open', 'Open (no ticket required)'), ('ticket_required', 'Ticket required')], default='', help_text="Leave blank to inherit the event's default policy.", max_length=20, verbose_name='Parent Check-In Policy'),
        ),
    ]
