# Generated by Django 5.2.8 on 2026-07-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_parent_checkin_policy_default_and_more'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='registration',
            field=models.ForeignKey(blank=True, help_text='Set only for tickets created via public self-serve registration; staff-created tickets leave this null and are unaffected.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='registrations.registration', verbose_name='Registration'),
        ),
        migrations.AddField(
            model_name='sessionticket',
            name='registration',
            field=models.ForeignKey(blank=True, help_text='Set only for tickets created via public self-serve registration; staff-created tickets leave this null and are unaffected.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_tickets', to='registrations.registration', verbose_name='Registration'),
        ),
    ]
