# Generated by Django 5.2.8 on 2026-07-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventticket_registration_sessionticket_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for a free event. SEK only — Swish/Bankgiro are Sweden-only payment rails.', max_digits=8, null=True, verbose_name='Price'),
        ),
    ]
