# Generated by Django 5.2.8 on 2026-07-08 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='price_at_registration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Snapshotted once at submission — never recomputed even if the ticket type's price changes afterwards.", max_digits=8, null=True, verbose_name='Price At Registration'),
        ),
        migrations.AddField(
            model_name='sessionticket',
            name='price_at_registration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Snapshotted once at submission — never recomputed even if the ticket type's price changes afterwards.", max_digits=8, null=True, verbose_name='Price At Registration'),
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price')),
                ('per_attendee', models.BooleanField(default=True, help_text='Unchecked for a per-registration extra shared by the whole booking (e.g. a cabin, a parking pass with quantity > 1).', verbose_name='Per Attendee')),
                ('applies_to', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('either', 'Either')], default='either', max_length=10, verbose_name='Applies To')),
                ('requires_choice', models.BooleanField(default=False, verbose_name='Requires Choice')),
                ('required', models.BooleanField(default=False, help_text='Must-choose-one, e.g. accommodation — renders as radio, not an optional checkbox.', verbose_name='Required')),
                ('default_selected', models.BooleanField(default=False, help_text='For an opt-out extra (e.g. food included by default, guardian can decline) — never model an opt-out as a negative price.', verbose_name='Default Selected')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='events.event', verbose_name='Event')),
                ('session', models.ForeignKey(blank=True, help_text="Set for a session-scoped extra (e.g. one evening's dinner). Blank = event-wide.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='events.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'db_table': 'extras',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price Delta')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_rows', to='events.extra', verbose_name='Extra')),
            ],
            options={
                'verbose_name': 'Extra Choice',
                'verbose_name_plural': 'Extra Choices',
                'db_table': 'extra_choices',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('applies_to', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('either', 'Either')], default='either', max_length=10, verbose_name='Applies To')),
                ('min_birthdate', models.DateField(blank=True, help_text='Age-tier lower bound: attendee must be born on/after this date. Blank = no lower bound.', null=True, verbose_name='Minimum Birthdate')),
                ('max_birthdate', models.DateField(blank=True, help_text='Age-tier upper bound: attendee must be born on/before this date. Blank = no upper bound.', null=True, verbose_name='Maximum Birthdate')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='Available From')),
                ('available_until', models.DateTimeField(blank=True, help_text='E.g. an early-bird cutoff. Checked at submission time only — never recomputed for an existing registration.', null=True, verbose_name='Available Until')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden from the public form; only selectable via a direct link/code (e.g. volunteer tickets).', verbose_name='Hidden')),
                ('kind', models.CharField(choices=[('event', 'Whole event'), ('session_bundle', 'Session bundle (e.g. one day)')], default='event', max_length=20, verbose_name='Kind')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Null = unlimited. Schema placeholder only — not yet enforced anywhere; a future capacity-accounting pass reads this field.', null=True, verbose_name='Capacity')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-retire instead of deleting once any ticket references this type — see on_delete=PROTECT on EventTicket/SessionTicket.', verbose_name='Active')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='Event')),
                ('sessions', models.ManyToManyField(blank=True, help_text='Only used when kind=session_bundle — the sessions this ticket type covers (e.g. a single day of a multi-day event).', related_name='bundle_ticket_types', to='events.session', verbose_name='Sessions')),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
                'db_table': 'ticket_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='eventticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, help_text='Set only for itemized self-serve tickets (Phase 3+); null means a flat-price/staff/import ticket, unaffected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_tickets', to='events.tickettype', verbose_name='Ticket Type'),
        ),
        migrations.AddField(
            model_name='sessionticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, help_text='Set only for itemized self-serve tickets (Phase 3+); null means a flat-price/staff/import ticket, unaffected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_tickets', to='events.tickettype', verbose_name='Ticket Type'),
        ),
        migrations.AddIndex(
            model_name='extra',
            index=models.Index(fields=['event'], name='extras_event_i_5930ee_idx'),
        ),
        migrations.AddIndex(
            model_name='extra',
            index=models.Index(fields=['session'], name='extras_session_d16d56_idx'),
        ),
        migrations.AddIndex(
            model_name='extrachoice',
            index=models.Index(fields=['extra'], name='extra_choic_extra_i_4528bf_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event'], name='ticket_type_event_i_802d9e_idx'),
        ),
    ]
