# Generated by Django 5.2.8 on 2026-07-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventticket_price_at_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank for no closing deadline.', null=True, verbose_name='Registration Closes At'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, help_text="Public self-serve registration only accepts submissions from this moment on. Leave this AND 'closes at' both blank to keep self-serve registration off for this event entirely — the correct default for events not meant for public sign-up (staff-only events, imports).", null=True, verbose_name='Registration Opens At'),
        ),
    ]
