# Generated by Django 5.2.8 on 2026-07-09 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_registration_closes_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Matched case-insensitively. Unique per event.', max_length=50, verbose_name='Code')),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], default='fixed', max_length=10, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='0-100 for percent, kr for fixed. 0 is valid — a pure unlock code with no discount of its own (e.g. the ticket it unlocks is already 0 kr).', max_digits=8, verbose_name='Discount Value')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Null = unlimited.', null=True, verbose_name='Max Uses')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='Uses Count')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('applies_to_ticket_types', models.ManyToManyField(blank=True, help_text='Empty = discount computed over the whole itemized total. Non-empty = discount computed only over matching ticket lines.', related_name='discount_promo_codes', to='events.tickettype', verbose_name='Applies To Ticket Types')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='events.event', verbose_name='Event')),
                ('unlocks_ticket_types', models.ManyToManyField(blank=True, help_text="Hidden ticket types (TicketType.is_hidden) this code makes selectable — e.g. VIP2026 unlocking Weekend 2026's VIP type.", related_name='unlocking_promo_codes', to='events.tickettype', verbose_name='Unlocks Ticket Types')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'db_table': 'promo_codes',
                'indexes': [models.Index(fields=['event'], name='promo_codes_event_i_3b14a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'code'), name='unique_promo_code_per_event')],
            },
        ),
    ]
