# Generated by Django 5.2.8 on 2026-07-12 20:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Optional hex accent color (e.g. #2563EB) for the public registration page hero. Leave blank for the default brand color.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')], verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='event',
            name='header_image_url',
            field=models.URLField(blank=True, help_text="Optional hero image shown on the public registration page. Paste a hosted image URL — this system doesn't store uploaded images.", verbose_name='Header Image URL'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='max_per_required',
            field=models.PositiveIntegerField(blank=True, help_text='Only used with requires_ticket_type set. Max count of this ticket type per one ticket of the required type (e.g. 4 free family members per paid family ticket). Null = unlimited, but at least one of the required type is still mandatory.', null=True, verbose_name='Max Per Required'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='requires_ticket_type',
            field=models.ForeignKey(blank=True, help_text="If set, this ticket type may only be selected on a registration that also has at least one ticket of the required type (e.g. a free 'family member' type requiring a paid 'family ticket' type).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_ticket_types', to='events.tickettype', verbose_name='Requires Ticket Type'),
        ),
    ]
