# Generated by Django 5.2.8 on 2026-07-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_accent_color_event_header_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='cloned_from',
            field=models.ForeignKey(blank=True, help_text='Informational only — the extra this was duplicated from, if any. No live link: editing either copy never affects the other.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='events.extra', verbose_name='Cloned From'),
        ),
    ]
