# Generated by Django 5.2.8 on 2026-07-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_extra_cloned_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['event__name', 'start_time'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
    ]
