# Generated by Django 5.2.8 on 2026-08-14 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_options_alter_session_options'),
        ('registrations', '0006_alter_registration_created_new_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='price_at_registration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price this ticket was sold at. Editing a price is safe — tickets already sold keep the price they were sold at.', max_digits=8, null=True, verbose_name='Price At Registration'),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='registration',
            field=models.ForeignKey(blank=True, help_text='The registration this ticket came from, when a family signed up themselves online. Blank for tickets created by staff or brought in by an import.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='registrations.registration', verbose_name='Registration'),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, help_text='The ticket type the family chose when registering. Blank for tickets created by staff or brought in by an import.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_tickets', to='events.tickettype', verbose_name='Ticket Type'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='applies_to_ticket_types',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to take the discount off the whole order. Pick ticket types to take it off only those lines.', related_name='discount_promo_codes', to='events.tickettype', verbose_name='Applies To Ticket Types'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to let the code be used any number of times.', null=True, verbose_name='Max Uses'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='unlocks_ticket_types',
            field=models.ManyToManyField(blank=True, help_text='Hidden ticket types that this code makes selectable — e.g. VIP2026 unlocking the VIP type for Weekend 2026.', related_name='unlocking_promo_codes', to='events.tickettype', verbose_name='Unlocks Ticket Types'),
        ),
        migrations.AlterField(
            model_name='sessionticket',
            name='price_at_registration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price this ticket was sold at. Editing a price is safe — tickets already sold keep the price they were sold at.', max_digits=8, null=True, verbose_name='Price At Registration'),
        ),
        migrations.AlterField(
            model_name='sessionticket',
            name='registration',
            field=models.ForeignKey(blank=True, help_text='The registration this ticket came from, when a family signed up themselves online. Blank for tickets created by staff or brought in by an import.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_tickets', to='registrations.registration', verbose_name='Registration'),
        ),
        migrations.AlterField(
            model_name='sessionticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, help_text='The ticket type the family chose when registering. Blank for tickets created by staff or brought in by an import.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_tickets', to='events.tickettype', verbose_name='Ticket Type'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for no limit. This number is not enforced yet — setting 50 will not stop a 51st booking.', null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to take this ticket type out of use: it disappears from the registration form, and tickets already sold keep working.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='max_birthdate',
            field=models.DateField(blank=True, help_text='The attendee must be born on or before this date. Leave blank for no upper age limit.', null=True, verbose_name='Maximum Birthdate'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='max_per_required',
            field=models.PositiveIntegerField(blank=True, help_text="How many tickets of this type each required ticket allows (e.g. 4 free family members per paid family ticket). Leave blank for no limit — one required ticket is still needed. Only used when 'Requires ticket type' is set.", null=True, verbose_name='Max Per Required'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='min_birthdate',
            field=models.DateField(blank=True, help_text='The attendee must be born on or after this date. Leave blank for no lower age limit.', null=True, verbose_name='Minimum Birthdate'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='sessions',
            field=models.ManyToManyField(blank=True, help_text='The sessions this ticket covers (e.g. a single day of a multi-day event). Only used when the kind above is a session bundle.', related_name='bundle_ticket_types', to='events.session', verbose_name='Sessions'),
        ),
    ]
