# Generated by Django 5.2.8 on 2026-08-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_eventticket_price_at_registration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
