# Generated by Django 5.2.8 on 2026-08-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='applies_to',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('either', 'Either')], default='either', help_text='Who may pick this ticket type on the public registration form — Child, Parent, or Either. Staff can still assign it to anyone by hand in the admin, regardless of this setting.', max_length=10, verbose_name='Applies To'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='max_birthdate',
            field=models.DateField(blank=True, help_text="The attendee must be born on or before this date (inclusive). This is a fixed calendar date you choose — commonly the event's start date — not a recalculated age, so it isn't re-checked as the event runs: a birthday partway through the event doesn't move anyone across the boundary. Leave blank for no upper age limit.", null=True, verbose_name='Maximum Birthdate'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='min_birthdate',
            field=models.DateField(blank=True, help_text='The attendee must be born on or after this date (inclusive). Leave blank for no lower age limit; leave both bounds blank to skip the age check for this ticket type entirely.', null=True, verbose_name='Minimum Birthdate'),
        ),
    ]
