# Generated by Django 5.2.8 on 2026-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0018_alter_tickettype_applies_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettype",
            name="max_birthdate",
            field=models.DateField(
                blank=True,
                help_text='The attendee must be born on or before this date (inclusive) — the youngest-age cutoff. Age is judged once, on the event\'s start date, and never recomputed as the event runs: a birthday partway through the event doesn\'t move anyone across the boundary. Because of that, this must land exactly on an anniversary of the event\'s start date (e.g. that date, 12 years earlier, for a "12 and under" cutoff). Leaving this blank does not mean "unconfigured" — it deliberately means anyone may hold this ticket type, with no upper age limit at all.',
                null=True,
                verbose_name="Maximum Birthdate",
            ),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="min_birthdate",
            field=models.DateField(
                blank=True,
                help_text="The attendee must be born on or after this date (inclusive) — the oldest-age cutoff. Age is judged once, on the event's start date, and never recomputed: the rule is age at event start, full stop, so this must land exactly one day after an anniversary of that date (e.g. the day after the event's start date, 18 years earlier, to exclude anyone who has already turned 18). Leaving this blank does not mean \"unconfigured\" — it deliberately means anyone may hold this ticket type, with no lower age limit at all. Leave both bounds blank to skip the age check for this ticket type entirely, on purpose.",
                null=True,
                verbose_name="Minimum Birthdate",
            ),
        ),
    ]
