# Generated by Django 5.2.8 on 2026-06-28 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_add_external_ticket_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('event_start_date', models.DateField(verbose_name='Event Start Date')),
                ('event_end_date', models.DateField(verbose_name='Event End Date')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('unique_children', models.PositiveIntegerField(default=0, verbose_name='Unique Children')),
                ('total_checkins', models.PositiveIntegerField(default=0, verbose_name='Total Check-Ins')),
                ('data', models.JSONField(verbose_name='Snapshot Data')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='events.event', verbose_name='Event')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
            ],
            options={
                'verbose_name': 'Event Report',
                'verbose_name_plural': 'Event Reports',
                'db_table': 'event_reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['event'], name='event_repor_event_i_5e6f5e_idx'), models.Index(fields=['-generated_at'], name='event_repor_generat_1d6cce_idx')],
            },
        ),
    ]
