# Generated by Django 5.2.8 on 2026-07-07 18:35

import django.db.models.deletion
import registrations.models
import registrations.tokens
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_event_parent_checkin_policy_default_and_more'),
        ('families', '0013_backfill_health_consent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending email verification'), ('confirmed', 'Confirmed'), ('pending_payment', 'Pending payment'), ('pending_review', 'Pending staff review'), ('cancelled', 'Cancelled')], default='pending_verification', max_length=32, verbose_name='Status')),
                ('reference_code', models.CharField(default=registrations.tokens.generate_unique_reference_code, help_text='Short code shown to the guardian for support lookups.', max_length=8, unique=True, verbose_name='Reference Code')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('verification_token_hash', models.CharField(help_text='SHA-256 hash of the one-time token sent by email.', max_length=64, unique=True, verbose_name='Verification Token Hash')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('verification_sent_at', models.DateTimeField(blank=True, help_text='Tracks the resend cooldown for a still-pending registration.', null=True, verbose_name='Verification Email Last Sent At')),
                ('expires_at', models.DateTimeField(default=registrations.models.default_expires_at, help_text='When an unverified registration becomes eligible for the expiry sweep.', verbose_name='Expires At')),
                ('created_new_family', models.BooleanField(default=True, help_text='True if this submission materialized a brand-new family (the phase-1 default). The expiry sweep only hard-deletes the family/children/tickets it created — it must never delete a pre-existing family.', verbose_name='Created New Family')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Event')),
                ('family', models.ForeignKey(help_text='The family materialized by this submission.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='families.family', verbose_name='Family')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'db_table': 'registrations',
                'indexes': [models.Index(fields=['status', 'expires_at'], name='registratio_status_032647_idx'), models.Index(fields=['event', 'contact_email'], name='registratio_event_i_32e01b_idx')],
            },
        ),
    ]
