# Generated by Django 5.2.8 on 2026-07-07 20:01

import django.db.models.deletion
import registrations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='expires_at',
            field=models.DateTimeField(default=registrations.models.default_expires_at, help_text='When this registration becomes eligible for the expiry sweep — the verification TTL while pending_verification, reset to the payment TTL when entering pending_payment.', verbose_name='Expires At'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount')),
                ('currency', models.CharField(default='SEK', max_length=3, verbose_name='Currency')),
                ('method', models.CharField(blank=True, choices=[('swish', 'Swish'), ('bankgiro', 'Bankgiro'), ('manual_other', 'Other (manual)')], default='', help_text="Set only once marked paid — a guardian may pay via either rail, so it isn't known in advance.", max_length=20, verbose_name='Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_marked', to=settings.AUTH_USER_MODEL, verbose_name='Marked By')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='registrations.registration', verbose_name='Registration')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'indexes': [models.Index(fields=['status'], name='payments_status_d621e5_idx')],
            },
        ),
    ]
