# Generated by Django 5.2.8 on 2026-07-08 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventticket_price_at_registration_and_more'),
        ('families', '0013_backfill_health_consent_status'),
        ('registrations', '0002_alter_registration_expires_at_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Only >1 allowed for a per-registration extra (per_attendee=False).', verbose_name='Quantity')),
                ('price_at_registration', models.DecimalField(decimal_places=2, help_text='Snapshotted per-unit price (extra.price + choice.price_delta) at submission time — never recomputed afterwards.', max_digits=8, verbose_name='Price At Registration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('attendee', models.ForeignKey(blank=True, help_text='Null for a per-registration extra (extra.per_attendee=False).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_extras', to='families.attendee', verbose_name='Attendee')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_extras', to='events.extrachoice', verbose_name='Choice')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_extras', to='events.extra', verbose_name='Extra')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='registrations.registration', verbose_name='Registration')),
            ],
            options={
                'verbose_name': 'Registration Extra',
                'verbose_name_plural': 'Registration Extras',
                'db_table': 'registration_extras',
                'indexes': [models.Index(fields=['registration'], name='registratio_registr_8a5c43_idx')],
                'constraints': [models.UniqueConstraint(fields=('registration', 'extra', 'attendee'), name='unique_registration_extra_attendee')],
            },
        ),
    ]
