# Generated by Django 5.2.8 on 2026-07-09 07:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_registrationextra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('received', 'Received'), ('refunded', 'Refunded'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='Kind')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Always positive — kind determines the sign of its effect on the payment's balance.", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_events_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registrations.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Event',
                'verbose_name_plural': 'Payment Events',
                'db_table': 'payment_events',
                'indexes': [models.Index(fields=['payment'], name='payment_eve_payment_898d20_idx')],
            },
        ),
    ]
