# Generated by Django 5.2.8 on 2026-07-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_promocode'),
        ('registrations', '0004_alter_payment_status_paymentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshotted once at submission (P2) — never recomputed, even if the promo code is edited afterwards.', max_digits=8, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='registration',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.promocode', verbose_name='Promo Code'),
        ),
    ]
