# Generated by Django 5.2.8 on 2026-08-14 08:51

import django.db.models.deletion
import registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0015_alter_attendee_options_alter_child_options_and_more'),
        ('registrations', '0005_registration_discount_amount_registration_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_new_family',
            field=models.BooleanField(default=True, help_text='Checked when this registration created a new family. If it is removed for being unfinished, only the family and tickets it created go with it — an existing family is never touched.', verbose_name='Created New Family'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The discount this registration was given. Editing the promo code afterwards is safe — it does not change what this family was charged.', max_digits=8, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='expires_at',
            field=models.DateTimeField(default=registrations.models.default_expires_at, help_text='When an unfinished registration is removed automatically. The deadline is extended once the guardian confirms their email address, to give them time to pay.', verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='family',
            field=models.ForeignKey(help_text='The family this registration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='families.family', verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='registrationextra',
            name='attendee',
            field=models.ForeignKey(blank=True, help_text='Leave blank for an extra that belongs to the whole booking rather than to one attendee.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_extras', to='families.attendee', verbose_name='Attendee'),
        ),
        migrations.AlterField(
            model_name='registrationextra',
            name='price_at_registration',
            field=models.DecimalField(decimal_places=2, help_text='The price per unit this extra was sold at. Editing a price is safe — extras already sold keep the price they were sold at.', max_digits=8, verbose_name='Price At Registration'),
        ),
        migrations.AlterField(
            model_name='registrationextra',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='More than 1 is only allowed for an extra that belongs to the whole booking rather than to one attendee.', verbose_name='Quantity'),
        ),
    ]
