# Generated by Django 5.2.8 on 2026-08-16 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_alter_registration_created_new_family_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='kind',
            field=models.CharField(choices=[('received', 'Received'), ('refunded', 'Refunded'), ('adjustment', 'Adjustment'), ('charged', 'Charge')], max_length=20, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Free text for any event. Mandatory for a Charge — raising what a family owes must always say why.', max_length=255, verbose_name='Note'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'charged'), ('note', ''), _negated=True), name='payment_event_charge_requires_note', violation_error_message='A charge must include a reason in its note.'),
        ),
    ]
