# Generated by Django 5.2.8 on 2025-11-23 11:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_participation_date",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "families",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("birthdate", models.DateField()),
                ("allergies", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "qr_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "last_participation_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "db_table": "children",
                "indexes": [
                    models.Index(
                        fields=["qr_token"], name="children_qr_toke_98cb5c_idx"
                    ),
                    models.Index(
                        fields=["last_name"], name="children_last_na_7c9895_idx"
                    ),
                    models.Index(fields=["family"], name="children_family__fb1a34_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("relationship_type", models.CharField(max_length=64)),
                (
                    "last_participation_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "db_table": "parents",
                "indexes": [
                    models.Index(fields=["family"], name="parents_family__12cac8_idx")
                ],
            },
        ),
    ]
