# Generated by Django 5.2.8 on 2025-12-02 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterField(
            model_name='child',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birthdate',
            field=models.DateField(verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='families.family', verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_participation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Participation Date'),
        ),
        migrations.AlterField(
            model_name='child',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='child',
            name='qr_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='QR Token'),
        ),
        migrations.AlterField(
            model_name='family',
            name='last_participation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Participation Date'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='families.family', verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_participation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Participation Date'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='relationship_type',
            field=models.CharField(max_length=64, verbose_name='Relationship Type'),
        ),
    ]
