# Generated by Django 5.2.8 on 2025-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_child_options_alter_family_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Last Name'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['last_name'], name='families_last_na_e36008_idx'),
        ),
    ]
