# Generated by Django 5.2.8 on 2025-12-06 16:54

from django.db import migrations


def populate_family_last_names(apps, schema_editor):
    """
    Populate family last_name field by deriving from the first child's last name.
    This is a reasonable default since siblings typically share a last name.
    """
    Family = apps.get_model('families', 'Family')
    Child = apps.get_model('families', 'Child')

    for family in Family.objects.all():
        if not family.last_name:  # Only populate if empty
            first_child = family.children.first()
            if first_child:
                family.last_name = first_child.last_name
                family.save(update_fields=['last_name'])


def reverse_populate_family_last_names(apps, schema_editor):
    """
    Reverse migration: clear all family last names.
    """
    Family = apps.get_model('families', 'Family')
    Family.objects.all().update(last_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_family_last_name_family_families_last_na_e36008_idx'),
    ]

    operations = [
        migrations.RunPython(populate_family_last_names, reverse_populate_family_last_names),
    ]
