# Generated by Django 5.2.8 on 2025-12-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_auto_20251206_1654'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='child',
            name='children_qr_toke_98cb5c_idx',
        ),
        migrations.RemoveField(
            model_name='child',
            name='qr_token',
        ),
    ]
