# Generated by Django 5.2.8 on 2026-03-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_remove_child_children_qr_toke_98cb5c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='external_booking_id',
            field=models.CharField(blank=True, help_text="Booking ID from the external registration system (e.g. '10869').", max_length=255, null=True, unique=True, verbose_name='External Booking ID'),
        ),
    ]
