# Generated by Django 5.2.8 on 2026-03-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_add_external_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
    ]
