# Generated by Django 5.2.8 on 2026-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_allow_null_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email_locked',
            field=models.BooleanField(default=False, help_text='When checked, re-imports will not overwrite this email address.', verbose_name='Email Locked'),
        ),
        migrations.AddField(
            model_name='parent',
            name='phone_locked',
            field=models.BooleanField(default=False, help_text='When checked, re-imports will not overwrite this phone number.', verbose_name='Phone Locked'),
        ),
    ]
