# Generated by Django 5.2.8 on 2026-07-04 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("families", "0011_convert_child_parent_to_mti"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="anonymized_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when GDPR retention anonymization scrubbed this attendee's PII.",
                null=True,
                verbose_name="Anonymized At",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="health_consent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Health Consent Recorded At"
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="health_consent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_consents_given",
                to="families.parent",
                verbose_name="Health Consent Given By",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="health_consent_notice_version",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Health Consent Notice Version",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="health_consent_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "No health information indicated"),
                    ("granted", "Guardian consented to recording details"),
                    ("declined", "Guardian declined to have details recorded"),
                    ("withdrawn", "Guardian withdrew previously granted consent"),
                    ("needs_reconfirmation", "Consent needs to be reconfirmed"),
                ],
                default="not_applicable",
                max_length=32,
                verbose_name="Health Data Consent Status",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="anonymized_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when GDPR retention anonymization scrubbed this family's PII.",
                null=True,
                verbose_name="Anonymized At",
            ),
        ),
    ]
