# Generated by Django 5.2.8 on 2026-07-10 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0013_backfill_health_consent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='parent',
            name='health_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Health Consent Recorded At'),
        ),
        migrations.AddField(
            model_name='parent',
            name='health_consent_by',
            field=models.ForeignKey(blank=True, help_text="Whoever attested to this consent decision — at initial registration, the registrant present filling in the form on behalf of the whole party (same attestor as a child's consent); may be this same parent when self-attesting.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_health_consents_attested', to='families.parent', verbose_name='Health Consent Given By'),
        ),
        migrations.AddField(
            model_name='parent',
            name='health_consent_notice_version',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Health Consent Notice Version'),
        ),
        migrations.AddField(
            model_name='parent',
            name='health_consent_status',
            field=models.CharField(choices=[('not_applicable', 'No health information indicated'), ('granted', 'Consented to recording details'), ('declined', 'Declined to have details recorded'), ('withdrawn', 'Withdrew previously granted consent'), ('needs_reconfirmation', 'Consent needs to be reconfirmed')], default='not_applicable', max_length=32, verbose_name='Health Data Consent Status'),
        ),
        migrations.AddField(
            model_name='parent',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
