# Generated by Django 5.2.8 on 2026-07-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0014_parent_allergies_parent_health_consent_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Attendee', 'verbose_name_plural': 'Attendees'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['last_name'], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
    ]
