# Generated by Django 5.2.8 on 2026-08-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0015_alter_attendee_options_alter_child_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['last_name'], 'permissions': [('export_family_dsar', "Can export a family's data (GDPR access)"), ('erase_family_dsar', "Can erase a family's data (GDPR erasure)")], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
    ]
