# Generated by Django 5.2.8 on 2025-11-23 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("families", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
                    ),
                    models.Index(fields=["user"], name="audit_logs_user_id_73c422_idx"),
                    models.Index(
                        fields=["entity_type"], name="audit_logs_entity__4f758f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CheckInRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "picked_up_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "check_in_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkins_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "check_out_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_records",
                        to="families.child",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_records",
                        to="events.session",
                    ),
                ),
            ],
            options={
                "db_table": "check_in_records",
                "indexes": [
                    models.Index(
                        fields=["child"], name="check_in_re_child_i_5f734e_idx"
                    ),
                    models.Index(
                        fields=["session"], name="check_in_re_session_88b7be_idx"
                    ),
                    models.Index(
                        fields=["check_in_staff"], name="check_in_re_check_i_49692f_idx"
                    ),
                    models.Index(
                        fields=["check_out_staff"],
                        name="check_in_re_check_o_263aea_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child", "session", "check_in_time"),
                        name="unique_check_in_per_session",
                    )
                ],
            },
        ),
    ]
