# Generated by Django 5.2.8 on 2025-12-02 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
        ('events', '0002_alter_event_options_alter_session_options_and_more'),
        ('families', '0002_alter_child_options_alter_family_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinrecord',
            options={'verbose_name': 'Check-In Record', 'verbose_name_plural': 'Check-In Records'},
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='label_printed',
            field=models.BooleanField(default=False, verbose_name='Label Printed'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Label Printed At'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='label_printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labels_printed', to=settings.AUTH_USER_MODEL, verbose_name='Label Printed By'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='check_in_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins_performed', to=settings.AUTH_USER_MODEL, verbose_name='Check-In Staff'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Check-In Time'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='check_out_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_performed', to=settings.AUTH_USER_MODEL, verbose_name='Check-Out Staff'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-Out Time'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_records', to='families.child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='picked_up_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Picked Up By'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_records', to='events.session', verbose_name='Session'),
        ),
        migrations.AddIndex(
            model_name='checkinrecord',
            index=models.Index(fields=['label_printed'], name='check_in_re_label_p_3f1e6a_idx'),
        ),
    ]
