# Generated by Django 5.2.8 on 2025-12-12 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_alter_checkinrecord_options_and_more'),
        ('events', '0004_migrate_old_tickets_to_polymorphic'),
        ('families', '0004_auto_20251206_1654'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrecord',
            name='supervised',
            field=models.BooleanField(default=False, help_text='Child is supervised by guardian, no explicit checkout required', verbose_name='Supervised'),
        ),
        migrations.AddIndex(
            model_name='checkinrecord',
            index=models.Index(fields=['supervised'], name='check_in_re_supervi_81fa8d_idx'),
        ),
    ]
