# Generated by Django 5.2.8 on 2025-12-15 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_checkinrecord_supervised_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='QR Code')),
                ('allocated_at', models.DateTimeField(blank=True, null=True, verbose_name='Allocated At')),
                ('released_at', models.DateTimeField(blank=True, help_text='When checkout occurred. Code returns to pool 24h after this.', null=True, verbose_name='Released At')),
                ('checkin_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_code', to='checkins.checkinrecord', verbose_name='Check-In Record')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'db_table': 'qr_codes',
                'indexes': [models.Index(fields=['code'], name='qr_codes_code_61971c_idx'), models.Index(fields=['released_at'], name='qr_codes_release_993684_idx')],
            },
        ),
    ]
