# Generated by Django 5.2.8 on 2026-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0006_repoint_checkin_to_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
