# Generated by Django 5.2.8 on 2026-08-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0007_auditlog_session_id_auditlog_source_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=64, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(max_length=255, verbose_name='Entity ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(max_length=64, verbose_name='Entity Type'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='supervised',
            field=models.BooleanField(default=False, help_text='The child stays with their guardian, so no separate check-out is needed.', verbose_name='Supervised'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='When the check-out happened. The code goes back into the pool 24 hours after this.', null=True, verbose_name='Released At'),
        ),
    ]
