# Generated by Django 5.2.8 on 2026-07-02 21:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_printer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
