# Generated by Django 5.2.8 on 2026-08-14 09:17

import django.db.models.deletion
import django.utils.timezone
import printing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0008_alter_auditlog_options_alter_auditlog_action_and_more'),
        ('printing', '0003_alter_printer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['name'], 'verbose_name': 'Printer', 'verbose_name_plural': 'Printers'},
        ),
        migrations.AlterModelOptions(
            name='printjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Print Job', 'verbose_name_plural': 'Print Jobs'},
        ),
        migrations.AlterField(
            model_name='printer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Seen At'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='token',
            field=models.CharField(default=printing.models.generate_printer_token, max_length=64, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Token Created At'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='token_revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Revoked At'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='checkins.checkinrecord', verbose_name='Check-In Record'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='printing.printer', verbose_name='Printer'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
