# Generated by Django 5.2.8 on 2026-03-03 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_add_external_ticket_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImportConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_mappings', models.JSONField(default=dict, help_text="Maps booking prefix keys to 'full_event', a session UUID, or 'ignore'.", verbose_name='Field Mappings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_config', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Import Config',
                'verbose_name_plural': 'Event Import Configs',
                'db_table': 'import_configs',
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('source_file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Source File Name')),
                ('log', models.JSONField(default=list, help_text='Array of per-booking log entries.', verbose_name='Log')),
                ('summary', models.JSONField(default=dict, help_text='Aggregated import statistics.', verbose_name='Summary')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='imports.eventimportconfig', verbose_name='Import Config')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to=settings.AUTH_USER_MODEL, verbose_name='Triggered By')),
            ],
            options={
                'verbose_name': 'Import Run',
                'verbose_name_plural': 'Import Runs',
                'db_table': 'import_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
