# Generated by Django 5.2.8 on 2026-03-04 20:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('login_url', models.URLField(max_length=2048, verbose_name='Login URL')),
                ('export_url', models.URLField(max_length=2048, verbose_name='Export URL')),
                ('export_body', models.TextField(blank=True, default='', help_text='Raw form-encoded body to POST to export_url. Paste from browser network capture.', verbose_name='Export POST Body')),
                ('credentials', models.BinaryField(blank=True, null=True, verbose_name='Credentials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'import_providers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='eventimportconfig',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs', to='imports.importprovider', verbose_name='Import Provider'),
        ),
    ]
