# Generated by Django 5.2.8 on 2026-03-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_import_source_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='raw_data',
            field=models.JSONField(blank=True, default=None, help_text='Raw parsed JSON from the import source, for debugging.', null=True, verbose_name='Raw Data'),
        ),
    ]
