# Generated by Django 5.2.8 on 2026-08-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_add_raw_data_to_import_run'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importsource',
            options={'ordering': ['name'], 'verbose_name': 'Import Source', 'verbose_name_plural': 'Import Sources'},
        ),
        migrations.AlterField(
            model_name='importsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
