import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _


class EventReport(models.Model):
    """
    A persisted snapshot of aggregate (non-PII) statistics for an event and its
    sessions.

    Reports are generated *before* PII (children, parents, families, check-in
    records) is deleted for data-retention reasons. The snapshot stores only
    aggregate numbers in ``data`` plus a few denormalized event fields, so the
    figures survive deletion of the underlying records and even the event row.
    Anything not captured at generation time cannot be recomputed later.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    event = models.ForeignKey(
        "events.Event",
        related_name="reports",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Event"),
    )
    # Denormalized so the snapshot is self-contained if the event is removed.
    event_name = models.CharField(max_length=255, verbose_name=_("Event Name"))
    event_start_date = models.DateField(verbose_name=_("Event Start Date"))
    event_end_date = models.DateField(verbose_name=_("Event End Date"))

    generated_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Generated At")
    )
    generated_by = models.ForeignKey(
        "accounts.AdminUser",
        related_name="event_reports",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Generated By"),
    )

    # Convenience columns for list/admin display; source of truth is ``data``.
    unique_children = models.PositiveIntegerField(
        default=0, verbose_name=_("Unique Children")
    )
    total_checkins = models.PositiveIntegerField(
        default=0, verbose_name=_("Total Check-Ins")
    )

    data = models.JSONField(verbose_name=_("Snapshot Data"))

    class Meta:
        db_table = "event_reports"
        verbose_name = _("Event Report")
        verbose_name_plural = _("Event Reports")
        ordering = ["-generated_at"]
        indexes = [
            models.Index(fields=["event"]),
            models.Index(fields=["-generated_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.event_name} report ({self.generated_at:%Y-%m-%d %H:%M})"
